// src/pages/SchedulesPage.js
import React from 'react';
import './SchedulesPage.css'; // Import CSS

const SchedulesPage = () => {
  return (
    <div className="schedules-page-container">
      <h2>Your Project Schedules</h2>
      <p className="schedules-info-message">
        This page will display all your project schedules generated by AI. Select a project to view its detailed schedule and AI insights.
      </p>
      {/* Content for displaying schedules will go here */}
    </div>
  );
};

export default SchedulesPage;